import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAdminCourses, createCourse, updateCourse, deleteCourse } from '../api';
import { useAuth } from '../context/AuthContext';

const field = 'mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100';
const btn = 'rounded-lg px-4 py-2.5 text-sm font-semibold transition disabled:opacity-50';
const emptyCourse = { title: '', description: '', price: '', imageURL: '', contentURL: '' };

function CourseForm({ initial = emptyCourse, onSave, onCancel }) {
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const set = key => e => setForm(f => ({ ...f, [key]: e.target.value }));
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { await onSave({ ...form, price: Number(form.price) }); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="space-y-4"><div><label className="text-sm font-medium">Course title</label><input className={field} value={form.title} onChange={set('title')} required /></div><div><label className="text-sm font-medium">Description</label><textarea className={`${field} min-h-28`} placeholder="What will students learn? At least 30 characters." value={form.description} onChange={set('description')} required /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="text-sm font-medium">Amount (USD)</label><input className={field} type="number" min="0" step="0.01" value={form.price} onChange={set('price')} required /></div><div><label className="text-sm font-medium">Cover image URL</label><input className={field} type="url" value={form.imageURL} onChange={set('imageURL')} required /></div></div><div><label className="text-sm font-medium">Private course-content link</label><input className={field} type="url" placeholder="Google Drive, Notion, Dropbox, etc." value={form.contentURL} onChange={set('contentURL')} required /><p className="mt-1.5 text-xs text-slate-500">This stays private and is emailed automatically after a purchase.</p></div>{error && <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<div className="flex gap-3"><button disabled={busy} className={`${btn} bg-indigo-600 text-white hover:bg-indigo-700`}>{busy ? 'Saving…' : 'Save course'}</button>{onCancel && <button type="button" onClick={onCancel} className={`${btn} border border-slate-200 text-slate-700 hover:bg-slate-50`}>Cancel</button>}</div></form>;
}

function PayoutAccount() {
  const [form, setForm] = useState(() => JSON.parse(localStorage.getItem('sellerPayoutAccount') || '{"accountName":"","accountNumber":"","routingCode":""}')); const [saved, setSaved] = useState(false);
  const set = key => e => setForm(f => ({ ...f, [key]: e.target.value }));
  function save(e) { e.preventDefault(); localStorage.setItem('sellerPayoutAccount', JSON.stringify(form)); setSaved(true); }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="mb-5"><h2 className="text-lg font-bold">Payout account</h2><p className="mt-1 text-sm text-slate-500">Where you want to receive course earnings.</p></div><form onSubmit={save} className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Account holder<input className={field} value={form.accountName} onChange={set('accountName')} required /></label><label className="text-sm font-medium">Account number / UPI ID<input className={field} value={form.accountNumber} onChange={set('accountNumber')} required /></label><label className="text-sm font-medium">Bank / routing code<input className={field} value={form.routingCode} onChange={set('routingCode')} /></label><div className="sm:col-span-3 flex items-center gap-3"><button className={`${btn} bg-slate-900 text-white hover:bg-slate-700`}>Save payout account</button>{saved && <span className="text-sm font-medium text-emerald-600">Saved on this device.</span>}</div></form></section>;
}

export default function AdminDashboard() {
  const { adminToken, logoutAdmin } = useAuth(); const navigate = useNavigate(); const [courses, setCourses] = useState([]); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState(null);
  function refresh() { setLoading(true); return getAdminCourses(adminToken).then(setCourses).finally(() => setLoading(false)); }
  useEffect(() => { if (!adminToken) navigate('/admin/login'); else refresh(); }, [adminToken]);
  async function remove(id) { if (!window.confirm('Delete this course?')) return; await deleteCourse(id, adminToken); setCourses(c => c.filter(x => x._id !== id)); }
  const saveNew = async data => { await createCourse(data, adminToken); setCreating(false); refresh(); }; const saveEdit = async data => { await updateCourse(editing._id, data, adminToken); setEditing(null); refresh(); };
  if (loading) return <div className="py-24 text-center text-slate-500">Loading seller studio…</div>;
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><header className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-indigo-600">Seller studio</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Manage your courses</h1><p className="mt-2 text-slate-500">Set your price, publish courses, and manage payouts.</p></div><button onClick={() => { logoutAdmin(); navigate('/'); }} className={`${btn} border border-slate-200 text-slate-700 hover:bg-white`}>Sign out</button></header><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">Your courses</h2><p className="text-sm text-slate-500">{courses.length} published</p></div><button onClick={() => { setEditing(null); setCreating(true); }} className={`${btn} bg-indigo-600 text-white hover:bg-indigo-700`}>+ Add course</button></div>{courses.length ? <div className="divide-y divide-slate-100">{courses.map(course => <div key={course._id} className="flex items-center gap-4 py-4"><img className="h-14 w-20 rounded-lg object-cover bg-slate-100" src={course.imageURL} alt=""/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{course.title}</p><p className="mt-0.5 text-sm text-slate-500">${course.price}</p></div><button onClick={() => setEditing(course)} className="text-sm font-semibold text-indigo-600 hover:text-indigo-800">Edit</button><button onClick={() => remove(course._id)} className="text-sm font-semibold text-rose-600 hover:text-rose-800">Delete</button></div>)}</div> : <p className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">No courses yet. Create your first course to start selling.</p>}</section><div className="mt-8"><PayoutAccount/></div>{(creating || editing) && <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-indigo-600">COURSE DETAILS</p><h2 className="text-xl font-bold">{editing ? 'Edit course' : 'New course'}</h2></div><button onClick={() => { setCreating(false); setEditing(null); }} className="text-2xl text-slate-400 hover:text-slate-700">×</button></div><CourseForm initial={editing || emptyCourse} onSave={editing ? saveEdit : saveNew} onCancel={() => { setCreating(false); setEditing(null); }}/></section></div>}</main>;
}
