import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { adminLogin, adminSignup } from '../api';
import { useAuth } from '../context/AuthContext';
const input = 'mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100';
export default function AdminAuth({ defaultTab = 'login' }) {
 const [tab,setTab]=useState(defaultTab),[form,setForm]=useState({email:'',password:'',firstName:'',lastName:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false); const {loginAdmin}=useAuth(), navigate=useNavigate(); const set=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{if(tab==='signup'){await adminSignup(form);setTab('login');setMessage('Seller account created. Sign in to open your studio.')}else{const data=await adminLogin(form);loginAdmin(data.authorization);navigate('/admin/dashboard')}}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <main className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl items-center justify-center px-4 py-10"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/50 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[.16em] text-indigo-600">Seller portal</p><h1 className="mt-2 text-2xl font-bold">{tab==='login'?'Welcome back':'Start selling'}</h1><p className="mt-2 text-sm text-slate-500">Create and price courses from your seller studio.</p><div className="mt-6 grid grid-cols-2 rounded-lg bg-slate-100 p-1"><button onClick={()=>setTab('login')} className={`rounded-md py-2 text-sm font-semibold ${tab==='login'?'bg-white shadow-sm':'text-slate-500'}`}>Sign in</button><button onClick={()=>setTab('signup')} className={`rounded-md py-2 text-sm font-semibold ${tab==='signup'?'bg-white shadow-sm':'text-slate-500'}`}>Create account</button></div><form onSubmit={submit} className="mt-6 space-y-4">{tab==='signup'&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">First name<input className={input} value={form.firstName} onChange={set('firstName')} required/></label><label className="text-sm font-medium">Last name<input className={input} value={form.lastName} onChange={set('lastName')} required/></label></div>}<label className="text-sm font-medium">Email<input className={input} type="email" value={form.email} onChange={set('email')} required/></label><label className="text-sm font-medium">Password<input className={input} type="password" value={form.password} onChange={set('password')} placeholder={tab==='signup'?'8+ characters, uppercase and number':''} required/></label><button disabled={busy} className="w-full rounded-lg bg-indigo-600 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-60">{busy?'Please wait…':tab==='login'?'Sign in':'Create seller account'}</button></form>{message&&<p className={`mt-4 rounded-lg px-3 py-2 text-sm ${message.startsWith('Seller')?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{message}</p>}<p className="mt-6 text-center text-sm text-slate-500">Here to learn? <Link to="/user/login" className="font-semibold text-indigo-600">Learner sign in</Link></p></section></main>
}
